import type { Metadata } from "next";
import "./globals.scss";

import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

import StoreProvider from "./_context/context";

import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // Retrieve cart if abandoned / saved
  const currentCookies = cookies().getAll()
  
  return (
    <html lang="en">
      <body className=''>
        <StoreProvider currentCookies={currentCookies}>
          <NavBar />          
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
