export const puzzledb = [
    {
        _id: '1',
        SKU: '', // barcode
        make: 'Jumbo',
        model: 'Wasgij Business as usual!',
        pieces: 1000,
        width: 70,
        height: 50,
        theme: 'Wasgij cartoon destiny',
        category: 'puzzle',
        description: 'De snelle zakenwereld draaide jarenlang om strakke, moderne kantoren met de nieuwste technologie en kek gekleed personeel met grafieken en tabellen binnen handbereik. Tenminste, totdat 2020 alles op zijn kop zette. Het kantoor anno nu maakt weliswaar nog altijd gebruik van moderne technologie om de zaken gesmeerd te laten verlopen, maar de omgeving van de medewerkers is ietwat chaotischer dan voorheen. Hun kantoorgenoten werken ook ietsje minder goed mee rond vergadertijd. Hoe anders ziet het kantoor van na 2020 er eigenlijk uit? Dat is het beeld dat jij puzzelt!',
        forAge: 18, // min-age, max-age?
        releaseYear: '2022',
        price: 15.00,
        isOnSale: true,
        originalPrice: 18.50,
        pic: ['/was_doboz.jpg', '/p2.webp', '/p3.png', '/p4.jpg'],
        condition: 100, // stars, %to color stars
        stock: 1,
        exchange: false,
        sellerId: '99',
        rating: 100, // stars, %to color stars
        // reviews: []
        // rentPrice: 0,
    },
    {
        _id: '2',
        make: 'Ravensburger',
        model: 'Disney Aristocats',
        pieces: 1000,
        width: 70,
        height: 50,
        theme: 'cartoon',
        category: 'puzzle',
        description: "Embark on a delightful journey with the Ravensburger Disney Collector's Edition Aristocats 1000-Piece Jigsaw Puzzle. Join Duchess, Thomas O'Malley, and their lovable feline friends as they whisk you away to a world of elegance, adventure, and music.",
        forAge: 14,
        releaseYear: '2024',
        price: 20,
        isOnSale: false,
        originalPrice: 0,
        pic: ['/pic0.jpg', '/pic1.jpg'],
        condition: 93,
        stock: 1,
        exchange: true,
        sellerId: '98',
        rating: 100,
    },
    {
        _id: '3',
        make: 'Ravensburger',
        model: 'Disney Princesses',
        pieces: 1000,
        width: 70,
        height: 50,
        theme: 'cartoon, disney',
        category: 'puzzle',
        description: 'princesses',
        forAge: 12,
        releaseYear: '2022',
        price: 15,
        isOnSale: false,
        originalPrice: 0,
        pic: ['/prins0.jpg', '/prins1.jpg'],
        condition: 80,
        stock: 1,
        exchange: false,
        sellerId: '99',
        rating: 100,
    },
    {
        _id: '4',
        make: 'Masterpieces',
        model: '1978 Corvette Pace Car',
        pieces: 750,
        width: 70,
        height: 50,
        theme: 'car, wheels, corvette',
        category: 'puzzle',
        description: "This MasterPieces 18-inch x 24 inches 750 piece Wheels Puzzle was created from a photograph taken by the very talented Linda Berman. Linda Berman is an award-winning photographer with special skills in Photoshop post-production. Her background in fine art elevates her work and transcends conventional photography. Her work has been exhibited and collected worldwide. The Wheels Puzzle Line features her photographs of timeless classic cars and classic car memorabilia. This puzzle features the Bob McDormand Automotive Museum is located in Canal Winchester OH. It is home to some rare VIN numbered Corvettes, including a 2015 model, VIN number 50 to commemorate Bob’s 50 years as a Chevrolet Corvette dealer. To reduce its impact on our environment, the chipboard used in this puzzle is made of recycled material.",
        forAge: 13,
        releaseYear: '2018',
        price: 22,
        isOnSale: false,
        originalPrice: 0,
        pic: ['/corvette0.jpg', '/corvette1.jpg'],
        condition: 100,
        stock: 3,
        exchange: true,
        sellerId: '97',
        rating: 100,
    },
    {
        _id: '5',
        make: 'Masterpieces',
        model: 'Triple Threat',
        pieces: 750,
        width: 70,
        height: 50,
        theme: 'car, wheels, corvette',
        category: 'puzzle',
        description: 'baeutiful imapala',
        forAge: 13,
        releaseYear: '2016',
        price: 22,
        isOnSale: false,
        originalPrice: 0,
        pic: ['/triple0.jpg', '/triple1.jpg'],
        condition: 100,
        stock: 5,
        exchange: true,
        sellerId: '97',
        rating: 100,
    },
    {
        _id: '6',
        make: 'Ravensburger',
        model: 'Disney Carnaval',
        pieces: 1000,
        width: 70,
        height: 50,
        theme: 'cartoon, disney',
        category: 'puzzle',
        description: '',
        forAge: 13,
        releaseYear: '2016',
        price: 12.20,
        isOnSale: true,
        originalPrice: 15.50,
        pic: ['/carneval0.jpg'],
        condition: 100,
        stock: 2,
        exchange: true,
        sellerId: '97',
        rating: 100,
    },
    {
        _id: '7',
        make: 'Trefl',
        model: 'African Elephants',
        pieces: 1000,
        width: 70,
        height: 50,
        theme: 'animal, elephant',
        category: 'puzzle',
        description: '',
        forAge: 13,
        releaseYear: '2016',
        price: 22,
        isOnSale: false,
        originalPrice: 0,
        pic: ['/elephants0.jpg'],
        condition: 100,
        stock: 2,
        exchange: true,
        sellerId: '97',
        rating: 100,
    },
    {
        _id: '8',
        make: 'Trefl',
        model: 'Amsterdam, Netherlands',
        pieces: 500,
        width: 70,
        height: 50,
        theme: 'city',
        category: 'puzzle',
        description: '',
        forAge: 13,
        releaseYear: '2016',
        price: 9.40,
        isOnSale: false,
        originalPrice: 0,
        pic: ['/ams0.jpg'],
        condition: 100,
        stock: 2,
        exchange: true,
        sellerId: '97',
        rating: 100,
    }
]